#+TITLE: emacs.d

I needed to rewrite my init away from the monolithic =.emacs= file, of
which this is an attempt.
  
I originally wanted to do an =init.org= version, but shied away when I
realized most people prefer the monolithic approach. I also didn't
want to use =org-babel-load-file= which seems slow (plus I don't
really want to include / depend on =org=). I realize I could have
written multiple org files so they are self documenting, but I think I
didn't want to deal with the minimal performance impact. Most of the
time, I'll have several emacs servers going. I don't want to wait
*too* long per new instance.

* Organization
  This is organized such that my =init.el= initiates and loads my
  =site/= files. It then loads anything under =site-lisp/=, which are
  lisp files or packages that I installed manually. Further, files
  stored in =unbp/= are those that I'm currently not using. Finally,
  =pkgs-%d.%d= is the directory that stores packages themselves.

  If you notice, files have a four-digit integer prefix. This allows
  files to be loaded in the order I want. Read the README.org under
  the =site/= directories for more information.

* Setup

  1. Clone
  #+BEGIN_SRC sh
  git clone git.yadev.io/emacs.d.git ~/.emacs.d
  #+END_SRC
  
  2. Open Emacs
  #+BEGIN_SRC sh
  emacs &
  # wait for emacs to get done installing packages etc
  #+END_SRC

  3. Restart Emacs and begin using

** Irony
  If you wish to use irony (code completion), install the following on your system:
  
  Linux:
  #+BEGIN_SRC sh
  apt install libclang-dev global
  #+END_SRC

  After installation is complete, install the server and you're done.
  #+BEGIN_SRC sh
  M-x irony-install-server
  #+END_SRC
  
** ERC
