#+TITLE: emacs.d

I needed to rewrite my init away from the monolithic =.emacs= file, of
which this is an attempt.
  
I originally wanted to do an =init.org= version, but shied away when I
realized most people prefer the monolithic approach. I also didn't
want to use =org-babel-load-file= which seems slow (plus I don't
really want to include / depend on =org=). I realize I could have
written multiple org files so they are self documenting, but I think I
didn't want to deal with the minimal performance impact. Most of the
time, I'll have several emacs servers going. I don't want to wait
*too* long per new instance.

* Organization
  This is organized such that my =init.el= initiates and loads my
  =lisp/= files. It then loads anything under =site-lisp/=, which are
  lisp files or packages that I installed manually. Further, files
  stored in =unbp/= are those that I'm currently not using. Finally,
  =pkgs-%d.%d= is the directory that stores packages themselves.

  If you notice, files have a four-digit integer prefix. This allows
  files to be loaded in the order I want. Read the README.org under
  the =lisp/= directories for more information.

* Setup

  1. Clone
  #+BEGIN_SRC sh
    # TODO
  #+END_SRC

  2. Open Emacs
  #+BEGIN_SRC sh
  emacs &
  # wait for emacs to get done installing packages etc
  #+END_SRC

  3. Restart Emacs and begin using

** Irony
  If you wish to use irony (code completion), install the following on your system:
  
  Linux:
  #+BEGIN_SRC sh
  apt install libclang-dev global
  #+END_SRC

  After installation is complete, install the server and you're done.
  #+BEGIN_SRC lisp
  M-x irony-install-server
  #+END_SRC
  
** ERC
To store erc information, I use the =erc/.ercauth.el= file. It may contain things like:

#+BEGIN_SRC lisp
(defun erc/join-ssl-freenode ()
  "Join irc.freenode.net with my personal credentials"

  (interactive)
  (setq erc-autojoin-channels-alist
	'(("freenode.net" "#emacs")))

  (erc-tls :server "irc.freenode.net" :port 6697
	   :nick "MY_NICK" :password "MY_COOL_LONG_PASSWORD"))

(defun erc/join-freenode ()
  "Join irc.freenode.net with my personal credentials"

  (interactive)
  (erc :server "irc.freenode.net" :port 6667
	   :nick "MY_NICK" :password "MY_COOL_LONG_PASSWORD"))
#+END_SRC

This file may contain several defun's for various servers etc.
